version: '3'

services:
  database:
    container_name: database
    build: ./database
    environment:
      POSTGRES_DB: delivery-go
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - my_network

  nats_stream:
    container_name: nats_stream
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - my_network

  delivery_app:
    container_name: delivery_app
    build:
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - database
      - nats_stream
    restart: on-failure

networks:
  my_network:
    driver: bridge
